require 'dotenv'
Dotenv.load



Vagrant.configure("2") do |config|
  #Define a common box for all VMs
  config.vm.box = "ubuntu/bionic64"

  #Defining Admin Server
  config.vm.define "Admin" do |adm|
      adm.vm.hostname = "Admin"
      adm.vm.network "private_network", ip: ENV['VM1_IP']
      adm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
      end
  end

  #Defining Target Server
  config.vm.define "Target" do |target|
      target.vm.hostname = "target"
      target.vm.network "private_network", ip: ENV['VM2_IP']
      target.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
      end
  end

  #Defining Load Balancer
  config.vm.define "Spare" do |spare|
      spare.vm.hostname = "spare"
      spare.vm.network "private_network", ip: ENV['VM3_IP']
      spare.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
      end
      
  end

end